javascripts:
  application:
    - public/javascripts/rails.js
    - public/javascripts/application.js

stylesheets:
  application:
    - public/stylesheets/web-app-theme/base.css
    - public/stylesheets/web-app-theme/themes/default/style.css
    - public/stylesheets/web-app-theme/override.css
    - public/stylesheets/git/style.css

  sessions:
    - public/stylesheets/web-app-theme/base.css
    - public/stylesheets/web-app-theme/themes/default/style.css
    - public/stylesheets/web-app-theme/override.css
