javascripts:
  application:
    - public/javascripts/rails.js
    - public/javascripts/application.js

stylesheets:
  application:
    - public/stylesheets/compiled/style.css
    - public/stylesheets/compiled/handheld.css
