development:
  adapter: postgresql
  encoding: unicode
  database: rosa_development
  pool: 5
  username: anayden
  password: nfhtkrf

test:
  adapter: postgresql
  encoding: unicode
  database: rosa_test
  pool: 5
  username: anayden
  password: nfhtkrf

production:
  adapter: postgresql
  encoding: unicode
  database: rosa_production
  pool: 5
  username: rosa
  password:
