--- 
:Roles: 
- name: !binary |
    0JDQtNC80LjQvdC40YHRgtGA0LDRgtC+0YAg0YHQuNGB0YLQtdC80Ys=

  use_default: true
  use_default_for_owner: false
  rights: 
    auto_build_lists: 
    - index
    - create
    event_logs: 
    - index
    groups: 
    - update
    - index
    - create
    - show
    - edit
    - destroy
    - new
    repositories: 
    - index
    - create
    - show
    - add_project
    - remove_project
    - destroy
    - new
    collaborators: 
    - index
    - create
    - show
    - edit
    - add
    - update
    - destroy
    - new
    downloads: 
    - index
    platforms: 
    - index
    - create
    - show
    - destroy
    - new
    - unfreeze
    - easy_urpmi
    - edit
    projects: 
    - index
    - auto_build
    - edit
    - update
    - add_collaborators
    - process_build
    - create
    - show
    - build
    - destroy
    - new
    rpc: 
    - build_packet
    - platforms
    - project_versions
    - xe_index
    - xe_method_prefix
    - user_projects
    - build_status
    private_users: 
    - index
    - create
    - destroy
    products: 
    - product_status
    - create
    - show
    - edit
    - build
    - destroy
    - update
    - new
    build_lists: 
    - show
    - pre_build
    - index
    - filter
    - post_build
    - status_build
    - circle_build
    - new_bbdt
    - publish
    - all
    - cancel
    members: 
    - index
    - create
    - show
    - edit
    - update
    - destroy
    - new
    categories: 
    - index
    - platforms
    - create
    - show
    - edit
    - destroy
    - update
    - new
    users: 
    - index
    - create
    - show
    - edit
    - destroy
    - update
    - new
    privates: 
    - show
    roles: 
    - index
    - create
    - show
    - edit
    - destroy
    - update
    - new
    - load_from_dump
    - get_dump
    personal_repositories: 
    - change_visibility
    - settings
    - show
    - add_project
    - remove_project
  id: 1
  to: ""
  can_see: !map:ActiveSupport::HashWithIndifferentAccess 
    Project: 
    - open
    - hidden
    Platform: 
    - open
    - hidden
  "on": ""
- name: !binary |
    0JDQtNC80LjQvdC40YHRgtGA0LDRgtC+0YAg0L/Qu9Cw0YLRhNC+0YDQvNGL

  use_default: false
  use_default_for_owner: true
  rights: 
    groups: 
    - index
    - destroy
  id: 2
  to: ""
  can_see: !map:ActiveSupport::HashWithIndifferentAccess 
    Project: 
    - open
  "on": Platform
- name: !binary |
    0JDQtNC80LjQvdC40YHRgtGA0LDRgtC+0YAg0YDQtdC/0L7Qt9C40YLQvtGA
    0LjRjw==

  use_default: false
  use_default_for_owner: true
  rights: {}

  id: 3
  to: ""
  can_see: 
  "on": Repository
- name: !binary |
    0JDQtNC80LjQvdC40YHRgtGA0LDRgtC+0YAg0L/RgNC+0LXQutGC0LA=

  use_default: false
  use_default_for_owner: true
  rights: {}

  id: 4
  to: User
  can_see: 
  "on": Project
- name: !binary |
    0JDQtNC80LjQvdC40YHRgtGA0LDRgtC+0YAg0LPRgNGD0L/Qv9GL

  use_default: false
  use_default_for_owner: true
  rights: {}

  id: 5
  to: User
  can_see: 
  "on": Group
- name: !binary |
    0JDQtNC80LjQvdC40YHRgtGA0LDRgtC+0YAg0L/RgNC+0LTRg9C60YLQsA==

  use_default: false
  use_default_for_owner: false
  rights: {}

  id: 6
  to: ""
  can_see: 
  "on": Project
- name: !binary |
    0JzQsNC50L3RgtC10LnQvdC10YAg0L/RgNC+0LXQutGC0LA=

  use_default: true
  use_default_for_owner: false
  rights: {}

  id: 7
  to: ""
  can_see: 
  "on": Project
- name: !binary |
    0J/QvtC70YzQt9C+0LLQsNGC0LXQu9GMINC/0LvQsNGC0YTQvtGA0LzRiw==

  use_default: false
  use_default_for_owner: false
  rights: {}

  id: 8
  to: ""
  can_see: 
  "on": Platform
- name: !binary |
    0KPRh9Cw0YHRgtC90LjQuiDQs9GA0YPQv9C/0Ys=

  use_default: true
  use_default_for_owner: false
  rights: {}

  id: 9
  to: User
  can_see: 
  "on": Group
- name: !binary |
    0J/QvtC70YzQt9C+0LLQsNGC0LXQu9GMINGB0LjRgdGC0LXQvNGL

  use_default: true
  use_default_for_owner: false
  rights: 
    groups: 
    - index
    repositories: 
    - index
    platforms: 
    - index
    projects: 
    - show
    private_users: 
    - index
    build_lists: 
    - index
    products: 
    - show
    personal_repositories: 
    - show
  id: 10
  to: User
  can_see: 
  "on": ""
