production:
  action_mailer_host: "abf.rosalinux.ru"
  root_path: /share
  nginx_log: /srv/rosa_build/shared/log/nginx.access.log
  do-not-reply-email: do-not-reply@rosalab.ru
  project_name: ABF
  repo_project_name: ABF
  build_server_ip: 127.0.0.1
  build_server_port: 12555
  build_server_path: /xmlrpc
  product_builder_ip:
    mdv: 192.168.122.144
    nau5: 192.168.122.203
  product_builder_port: 12554
  product_builder_path: /xmlrpc
  distr_types: ['mdv']
